{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bookkeepersmc",
    "module": "Notebook-api-common",
    "version": "1.1.16+1.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "Notebook-api-common-1.1.16+1.20.5.jar",
          "url": "Notebook-api-common-1.1.16+1.20.5.jar",
          "size": 251461,
          "sha512": "69c9c41d05ee928cd749ea63a42a86c2cf912dac56d540ad61b1321950f1869d1f29fbda5b303cb11209f9a78163834d054f0c81fb197eebd50d65b75c0aab35",
          "sha256": "2ae61b1bd72a820791e073a4a1502be5848733696611b822ee871cd04de2a0aa",
          "sha1": "b700984202265dde3f387068c422e8c232d398a3",
          "md5": "14df272ac9d7032e2aece26ee013ccfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "Notebook-api-common-1.1.16+1.20.5.jar",
          "url": "Notebook-api-common-1.1.16+1.20.5.jar",
          "size": 251461,
          "sha512": "69c9c41d05ee928cd749ea63a42a86c2cf912dac56d540ad61b1321950f1869d1f29fbda5b303cb11209f9a78163834d054f0c81fb197eebd50d65b75c0aab35",
          "sha256": "2ae61b1bd72a820791e073a4a1502be5848733696611b822ee871cd04de2a0aa",
          "sha1": "b700984202265dde3f387068c422e8c232d398a3",
          "md5": "14df272ac9d7032e2aece26ee013ccfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-common-1.1.16+1.20.5-sources.jar",
          "url": "Notebook-api-common-1.1.16+1.20.5-sources.jar",
          "size": 206611,
          "sha512": "780588157fa1000ea0fec6e7ecac7631739f6004696f7b3e4e71ed1d9960a56a2521e26d49b79aea3ec889d37a7da79bf3289cfc958b9fefe3ac1b36a95b7151",
          "sha256": "0172e1e610b3ed7b1efb7afc7de28379aed4d49d164e40ac9d6588323a6bdf83",
          "sha1": "43c2e8d4b9fe6f9cb4580c0bc9531abbf85c18b7",
          "md5": "3f3b1d5c970e9d581297fc828d082950"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-common-1.1.16+1.20.5-javadoc.jar",
          "url": "Notebook-api-common-1.1.16+1.20.5-javadoc.jar",
          "size": 656034,
          "sha512": "89ccd1d6f10850ecd565741e2272005c33c85aacace5f83f9744934a298c5b1bd99e877f0d5668be06521890ea9eec57775097b414e2e15d064d79e0dee8c138",
          "sha256": "14e115e6a56ffb6d55f11341802f06da2022fdaae3a60290233fca369341fe70",
          "sha1": "4773e5eef4afd7a72727b307df8a2c9ce0bca540",
          "md5": "ec4288d179112f560cc3ce3a5da0ac83"
        }
      ]
    }
  ]
}
