{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "3.0.0.0-1.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-3.0.0.0-1.21.jar",
          "url": "BetterBiomes-Fabric-3.0.0.0-1.21.jar",
          "size": 2938242,
          "sha512": "e001269284f2962950053a6f0afed436f3b69eee7d4a1d0ed9a8c8e01816ed46d41ae2020e10bfdfdab951cb9c4ef77b7422a83e5358444e36d7d01cc54146f2",
          "sha256": "d7808fbcc3c13bc6471ac60b093175ed884ae08dd99fb01dbf34c3996d8641fd",
          "sha1": "409437ce83afc21cdc0895c695224928db3fc528",
          "md5": "758dbd26fd0f3e4edd74b8a789da0133"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.100.1+1.21"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.21-4.0.0.0"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "11.0.0-alpha.1"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-3.0.0.0-1.21.jar",
          "url": "BetterBiomes-Fabric-3.0.0.0-1.21.jar",
          "size": 2938242,
          "sha512": "e001269284f2962950053a6f0afed436f3b69eee7d4a1d0ed9a8c8e01816ed46d41ae2020e10bfdfdab951cb9c4ef77b7422a83e5358444e36d7d01cc54146f2",
          "sha256": "d7808fbcc3c13bc6471ac60b093175ed884ae08dd99fb01dbf34c3996d8641fd",
          "sha1": "409437ce83afc21cdc0895c695224928db3fc528",
          "md5": "758dbd26fd0f3e4edd74b8a789da0133"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-3.0.0.0-1.21-sources.jar",
          "url": "BetterBiomes-Fabric-3.0.0.0-1.21-sources.jar",
          "size": 305467,
          "sha512": "13c54acfb4dc5c38b0091d255103ad86a4adec5ab31f353440c79302b18f8fc09aee745b661dc3c6ff8114d4d7ac983189496855dce66994d110f3e3a5528e86",
          "sha256": "373fbf0d6a8b3588915e45ad19cf0c4cd37f5f5f45ae2ee0eee1eab559e6d077",
          "sha1": "ff014cd4e833f67d9c12d3111826e3f4df32e3bd",
          "md5": "a93911d285abc20f33159ff5b7366091"
        }
      ]
    }
  ]
}
