{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bookkeepersmc",
    "module": "Notebook-api-fabric",
    "version": "1.1.15+1.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.15+1.20.5"
          }
        }
      ],
      "files": [
        {
          "name": "Notebook-api-fabric-1.1.15+1.20.5.jar",
          "url": "Notebook-api-fabric-1.1.15+1.20.5.jar",
          "size": 246202,
          "sha512": "b5a33d58eaf78140e3e726de6042599fea404f8acfb5d67c1d2a6b0ccfe2ab15720667831b7457f8d5cdec85d6289d54136246bcae8d3e544228afe6c6916cfc",
          "sha256": "42c336b7a29140c63c0ca5b0de38e227c453c30b0c44355aa7332f973b455206",
          "sha1": "a275c10148a48d686b7a9e0935c70f50b3050e17",
          "md5": "420db6bd6d12f2438ee60e9a035dcda1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "Notebook-api-fabric-1.1.15+1.20.5.jar",
          "url": "Notebook-api-fabric-1.1.15+1.20.5.jar",
          "size": 246202,
          "sha512": "b5a33d58eaf78140e3e726de6042599fea404f8acfb5d67c1d2a6b0ccfe2ab15720667831b7457f8d5cdec85d6289d54136246bcae8d3e544228afe6c6916cfc",
          "sha256": "42c336b7a29140c63c0ca5b0de38e227c453c30b0c44355aa7332f973b455206",
          "sha1": "a275c10148a48d686b7a9e0935c70f50b3050e17",
          "md5": "420db6bd6d12f2438ee60e9a035dcda1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-fabric-1.1.15+1.20.5-sources.jar",
          "url": "Notebook-api-fabric-1.1.15+1.20.5-sources.jar",
          "size": 208654,
          "sha512": "9f7b7d114b6391e5870f6f631f01423668882df3aa459b81c467a7f9200d5bec8a77bc6256a8c7dbf1e208886c34130b44abcd83b9a1532175e946b74620e34f",
          "sha256": "24f5f6b438f06405a6bcb5ebc21401d51679f2741ba74664dd5f01edc44a3360",
          "sha1": "b66ea2868aa87d7e5cb1f228762bb80e693c67f1",
          "md5": "3c516f61dc4e5a5926c74af7c01f7e41"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-fabric-1.1.15+1.20.5-javadoc.jar",
          "url": "Notebook-api-fabric-1.1.15+1.20.5-javadoc.jar",
          "size": 83909,
          "sha512": "cc743b86730028f8c7df01f7bfbfa5bca649ba4ff048d03472b1d41059b1250da956f55595b96ac8a2fd749e206d8672c5b3767417238f08efbf3ff60de17f44",
          "sha256": "aabab69f6e9ae2167e9f2caa57a7064859e23a1a6110ea15fb1f6e88cb595816",
          "sha1": "cfff69db959b391c256b36b46197f03d869fb698",
          "md5": "c345e53e3fa6404d71a15e7a643087b5"
        }
      ]
    }
  ]
}
