{
  "formatVersion": "1.1",
  "component": {
    "group": "net.crypticverse.betterbiomes",
    "module": "BetterBiomes-Fabric",
    "version": "2.2.1.0-1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.1.17"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.2.1.0-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.2.1.0-1.20.4.jar",
          "size": 2886144,
          "sha512": "cafcbc87bdb70da395daed26c8a1b7c1bc5ae45c1ee92576606109ee2a0c99f34792eb5e57e61659cafd44db3929cf45ef0a3d7d84601033d267d4b182a022bc",
          "sha256": "1dedb3ee0475885f94b048443b819d7f2b038950d47fef13112176df3c16e6b4",
          "sha1": "8534b8c1aeb5c341dc093370d6a9fa113ac2628f",
          "md5": "a4d43197d5389127168e67f73959eb7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.shedaniel.cloth",
          "module": "cloth-config-fabric",
          "version": {
            "requires": "13.0.121"
          },
          "excludes": [
            {
              "group": "net.fabricmc.fabric-api",
              "module": "*"
            }
          ]
        },
        {
          "group": "dev.architectury",
          "module": "architectury-fabric",
          "version": {
            "requires": "11.1.17"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.11"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.11+1.20.4"
          }
        },
        {
          "group": "com.github.glitchfiend",
          "module": "TerraBlender-fabric",
          "version": {
            "requires": "1.20.4-3.3.0.12"
          }
        },
        {
          "group": "com.terraformersmc.terraform-api",
          "module": "terraform-wood-api-v1",
          "version": {
            "requires": "9.0.0"
          }
        },
        {
          "group": "me.shedaniel",
          "module": "RoughlyEnoughItems-fabric",
          "version": {
            "requires": "14.0.688"
          }
        }
      ],
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.2.1.0-1.20.4.jar",
          "url": "BetterBiomes-Fabric-2.2.1.0-1.20.4.jar",
          "size": 2886144,
          "sha512": "cafcbc87bdb70da395daed26c8a1b7c1bc5ae45c1ee92576606109ee2a0c99f34792eb5e57e61659cafd44db3929cf45ef0a3d7d84601033d267d4b182a022bc",
          "sha256": "1dedb3ee0475885f94b048443b819d7f2b038950d47fef13112176df3c16e6b4",
          "sha1": "8534b8c1aeb5c341dc093370d6a9fa113ac2628f",
          "md5": "a4d43197d5389127168e67f73959eb7b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BetterBiomes-Fabric-2.2.1.0-1.20.4-sources.jar",
          "url": "BetterBiomes-Fabric-2.2.1.0-1.20.4-sources.jar",
          "size": 308273,
          "sha512": "56d273d0feebea0b46153f23e3ad42e1c741b48c76b4257d8c0a46f14164b7f1de518098a6889e7d1ac990c7c09e2b8b18265690094b84700e5e18ff5845160b",
          "sha256": "0430e51a25884535c26d41c5d6693f9118e8ad4b09831a7648212199125bba64",
          "sha1": "809754dcd6e9c7dfc4c682454a1ed6ab083a55ac",
          "md5": "4bf0719dc6e10612fc6669678fb1a0fb"
        }
      ]
    }
  ]
}
