{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bookkeepersmc",
    "module": "Notebook-api-fabric-24w14a",
    "version": "1.1.14+1.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.14+1.20.5"
          }
        }
      ],
      "files": [
        {
          "name": "Notebook-api-fabric-24w14a-1.1.14+1.20.5.jar",
          "url": "Notebook-api-fabric-24w14a-1.1.14+1.20.5.jar",
          "size": 214732,
          "sha512": "25e0d4f03abff2a838f5ae4112f8200a523706bb8e5facc94da08361badc4bd5dfaf29b016b9d96c1692b49a6d07b4f5ec30937a6218956f53ea4efd89b37bea",
          "sha256": "6ba9da62df54e2a940b9fe13f265529f90637e653ee301a16390c68df584ae8f",
          "sha1": "01cc65a1ae6649bbf5ada5ac70d912c58412dca8",
          "md5": "6b5e5b496fe9791b54cc20d872a91ff4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "Notebook-api-fabric-24w14a-1.1.14+1.20.5.jar",
          "url": "Notebook-api-fabric-24w14a-1.1.14+1.20.5.jar",
          "size": 214732,
          "sha512": "25e0d4f03abff2a838f5ae4112f8200a523706bb8e5facc94da08361badc4bd5dfaf29b016b9d96c1692b49a6d07b4f5ec30937a6218956f53ea4efd89b37bea",
          "sha256": "6ba9da62df54e2a940b9fe13f265529f90637e653ee301a16390c68df584ae8f",
          "sha1": "01cc65a1ae6649bbf5ada5ac70d912c58412dca8",
          "md5": "6b5e5b496fe9791b54cc20d872a91ff4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-fabric-24w14a-1.1.14+1.20.5-sources.jar",
          "url": "Notebook-api-fabric-24w14a-1.1.14+1.20.5-sources.jar",
          "size": 180234,
          "sha512": "857f4cce483d4f448eaa61460e80e329c503d765154bcc20914d057cfe56767478a2a7798a81eddd5dd7f4b546286b8858abb339d2e14fc7cef963a82651a5a7",
          "sha256": "4a1479ac79c40c26526d489fad321705312a212b42af5362cbd0b1ad0f31eea2",
          "sha1": "186a5c53cf607b7656c4342449071dcd2816874d",
          "md5": "b540923b76ff08a635156f823d76d13d"
        }
      ]
    }
  ]
}
