{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bookkeepersmc",
    "module": "Notebook-api-common",
    "version": "1.1.15+1.20.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "Notebook-api-common-1.1.15+1.20.5.jar",
          "url": "Notebook-api-common-1.1.15+1.20.5.jar",
          "size": 251461,
          "sha512": "8ebcddd5499d9c7a6f28f43fdfdc78de8e7da1c81c92813b4176b1c02078c674a1f4c1c807b09e354269353e6bdb84149c383adfdc094a78eb231dfcd36bc5b6",
          "sha256": "69795e2770ec85c693e652f090644603a9227706cb80fa2e977aaac488a45078",
          "sha1": "9b3089a11fd4fd82248e9837cc69c9bc21bc792f",
          "md5": "48906e9e904db7380dec962449f5a5e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "io.github.llamalad7",
          "module": "mixinextras-common",
          "version": {
            "requires": "0.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.23"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "Notebook-api-common-1.1.15+1.20.5.jar",
          "url": "Notebook-api-common-1.1.15+1.20.5.jar",
          "size": 251461,
          "sha512": "8ebcddd5499d9c7a6f28f43fdfdc78de8e7da1c81c92813b4176b1c02078c674a1f4c1c807b09e354269353e6bdb84149c383adfdc094a78eb231dfcd36bc5b6",
          "sha256": "69795e2770ec85c693e652f090644603a9227706cb80fa2e977aaac488a45078",
          "sha1": "9b3089a11fd4fd82248e9837cc69c9bc21bc792f",
          "md5": "48906e9e904db7380dec962449f5a5e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-common-1.1.15+1.20.5-sources.jar",
          "url": "Notebook-api-common-1.1.15+1.20.5-sources.jar",
          "size": 206611,
          "sha512": "a2301616ccb0ef61d2c8fb02dab8b00d0c98e094ce847bcdacfb3db04a6947e8c3321dad7f3e730b6ed436ac1ef2f2037b23bf4d8fb23b6d654cf5578463e39f",
          "sha256": "4d7ccc37bada9ab0d226c1965c916b4293acdcc5af29871d68ab80b466d3de3b",
          "sha1": "b1feb458cd908b866dfa84801149c19316f45a44",
          "md5": "d4c42c9932b4064596ea4cacdaf043d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Notebook-api-common-1.1.15+1.20.5-javadoc.jar",
          "url": "Notebook-api-common-1.1.15+1.20.5-javadoc.jar",
          "size": 656034,
          "sha512": "4dcb4ca05b5c556074f242dc698344e714ee15eedbad726c815bd9eee0ba1a08fdec61535fa8ba965479108f846ded32061ab4cd3b8393d5854d8883d51ab395",
          "sha256": "513c71fc477cd39d167ef9bd9d47651f87e3f736750324fe170e239bf2f0d392",
          "sha1": "e66cb24e0bb823c342eccb6cd5aa85c00ca2b245",
          "md5": "6de182253e14bbbb937eeeb91f0bbc58"
        }
      ]
    }
  ]
}
