{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bookkeepersmc",
    "module": "mercurymixin",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId": "e6xbbg6htvadbfm6byuyd6oamq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "mercurymixin-0.2.0.jar",
          "url": "mercurymixin-0.2.0.jar",
          "size": 41013,
          "sha512": "c8f3c394849aaf74057861bf50cdbfd81db0244f54cd01c1281b3dd56c66fdf517fef918a319ecfbc76e26da7cd28969397a7b99d68b068ba478a403ddc0dad4",
          "sha256": "cceb76e9f188367134613d0e716cd410123af964f0d40fd69d0dcebdac546b14",
          "sha1": "2823adb959563023bfc80c12eb36e6ee878cf215",
          "md5": "74dad53281587b0bad5ca63ba84883f5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "mercurymixin-0.2.0.jar",
          "url": "mercurymixin-0.2.0.jar",
          "size": 41013,
          "sha512": "c8f3c394849aaf74057861bf50cdbfd81db0244f54cd01c1281b3dd56c66fdf517fef918a319ecfbc76e26da7cd28969397a7b99d68b068ba478a403ddc0dad4",
          "sha256": "cceb76e9f188367134613d0e716cd410123af964f0d40fd69d0dcebdac546b14",
          "sha1": "2823adb959563023bfc80c12eb36e6ee878cf215",
          "md5": "74dad53281587b0bad5ca63ba84883f5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mercurymixin-0.2.0-javadoc.jar",
          "url": "mercurymixin-0.2.0-javadoc.jar",
          "size": 150599,
          "sha512": "79577f6c50cd2fc19f4cf0f7cde7e20099f1fcbea2a5a66a22debe81e0d3671bbf86fb7db6ec853b947fb57b567034dbd490a637ee11205eab84c996796d2c20",
          "sha256": "4d7dccaf3bcac3750157f0575516996df6b322e41b5caee31bf2f50ab9be4c7a",
          "sha1": "526804582b35652389a0eda2996334087dee5a58",
          "md5": "8eab079cc12b56f236c685c83257dd16"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mercurymixin-0.2.0-sources.jar",
          "url": "mercurymixin-0.2.0-sources.jar",
          "size": 23648,
          "sha512": "3ee182ab9852879d2f45a8d25af3c4a9759be0c10d4028084f2b615a46ba2e8d8e30bb111a75cced51856c1e04824b899e26c11491acca1d8252cf393e3933c1",
          "sha256": "997a68a26ea05b5fc70d96701797753ec93c3a1ca211489dcaeb77a668567cd1",
          "sha1": "4921f7d304808a31e94f0a43eb701097648e42a4",
          "md5": "4c0f09820f3c01331a2a571d9014f194"
        }
      ]
    }
  ]
}
