{
  "formatVersion": "1.1",
  "component": {
    "group": "com.bookkeepersmc",
    "module": "entrypoint-utils",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "entrypoint-utils-1.0.jar",
          "url": "entrypoint-utils-1.0.jar",
          "size": 31936,
          "sha512": "c92c49868ed7975b5d3de28da63434a2771ad48538c1492116dc85c121c90e01e71f89fc5eea59287716f84129c0ab6151bf7064a81aac6fe3bd0a62be51f693",
          "sha256": "e35ed23639a2242f573df78d54df21059e659749d477e9878a8f84e65c384ad7",
          "sha1": "c1e23e0cdcf218db51a495525b07acf41f7277f3",
          "md5": "1698f7322fa66638414737fa9a5cd7ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "net.jodah",
          "module": "typetools",
          "version": {
            "requires": "0.6.3"
          }
        }
      ],
      "files": [
        {
          "name": "entrypoint-utils-1.0.jar",
          "url": "entrypoint-utils-1.0.jar",
          "size": 31936,
          "sha512": "c92c49868ed7975b5d3de28da63434a2771ad48538c1492116dc85c121c90e01e71f89fc5eea59287716f84129c0ab6151bf7064a81aac6fe3bd0a62be51f693",
          "sha256": "e35ed23639a2242f573df78d54df21059e659749d477e9878a8f84e65c384ad7",
          "sha1": "c1e23e0cdcf218db51a495525b07acf41f7277f3",
          "md5": "1698f7322fa66638414737fa9a5cd7ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entrypoint-utils-1.0-javadoc.jar",
          "url": "entrypoint-utils-1.0-javadoc.jar",
          "size": 149255,
          "sha512": "2e5e79e0d91dddaf734b54599625c9c9a44bccca13690a2970d01f5e9938bd2c28d2cfdb214ba2541ba30f64b84b6beab960fc2cc9ac6d1459257f17627acef0",
          "sha256": "cb962fbe8008e66c7e5e3cbf6578aac49f8461d4c5327bc4e6f3b69f767c9779",
          "sha1": "1b14e4168143e6b3e3e2952fa50dfe4d9b80727e",
          "md5": "815109b13503965397b068ff229520b2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entrypoint-utils-1.0-sources.jar",
          "url": "entrypoint-utils-1.0-sources.jar",
          "size": 16542,
          "sha512": "d965821eeaeed0a3bf82150133f6cc383e487afe177fe83464a1ba369ecc50de37771b0878fed0f3542c4ab1540b3fa20a385ffb8878ca5bd7301c3d709c560a",
          "sha256": "68f2c9e5a57a7e454243c3a73b3f22a0577f48892d82bfde76daefb8bd73bede",
          "sha1": "f4edcf2203e8bfae3a4cfdade6d808fdaec3aff5",
          "md5": "d8d176f263bd57831a7baee628880708"
        }
      ]
    }
  ]
}
